# Лабораторная работа 3. Пакет Pandas

**Цель работы:** ознакомление с методом аппроксимации функций.

Продолжительность работы: - 4 часа.

Мягкий дедлайн (100 баллов): 23.10.2026

Жесткий дедлайн (50 баллов): 30.10.2026


Оценка за каждое задание указана в комментариях перед заданием.

Задание выполняется самостоятельно, в противном случае все причастные получат 0 баллов :)
Если вы нашли решение любого из заданий (или его части) в открытом источнике, необходимо указать ссылку на этот источник в отдельном блоке в конце своей работы.
В противном случае **работа также будет оценена в 0 баллов**.

In [2]:
score = 0

In [3]:
import numpy as np
import pandas as pd

Pandas — удобная библиотека для работы с табличными данными в Python, если данных не слишком много и они помещаются в оперативную память вашего компьютера. Несмотря на неэффективность реализации и некоторые проблемы, библиотека стала стандартом в анализе данных.

Основной объект в pandas — это DataFrame, представляющий собой таблицу с именованными колонками различных типов, индексом (может быть многоуровневым). DataFrame можно создавать, считывая таблицу из файла или задавая вручную из других объектов.

В этой части потребуется выполнить несколько небольших заданий. Можно пойти двумя путями: сначала изучить материалы, а потом приступить к заданиям, или же разбираться "по ходу". Выбирайте сами.

Материалы:
1. [Pandas за 10 минут из официального руководства](http://pandas.pydata.org/pandas-docs/stable/10min.html)
2. [Документация](http://pandas.pydata.org/pandas-docs/stable/index.html) (стоит обращаться, если не понятно, как вызывать конкретный метод)
3. [Примеры использования функционала](http://nbviewer.jupyter.org/github/justmarkham/pandas-videos/blob/master/pandas.ipynb)

Многие из заданий можно выполнить несколькими способами. Не существуют единственно верного, но попробуйте максимально задействовать арсенал pandas и ориентируйтесь на простоту и понятность вашего кода. Мы не будем подсказывать, что нужно использовать для решения конкретной задачи, попробуйте находить необходимый функционал сами (название метода чаще всего очевидно). В помощь вам документация, поиск и stackoverflow.

## Часть 1. Изучение набора данных

В этой части задания использование циклов запрещается и повлечет за собой снижение оценки. Использование <code>vectorize</code> и  <code>apply</code>, <code>apply_along_axis</code> крайне нежелательно.

Для каждой задачи из этого раздела вы должны написать код для получения ответа, а также дать текстовый ответ, если он предполагается.

На некоторые вопросы вы можете получить путём пристального взгляда на таблицу, но это не будет засчитываться. Вы в любом случае должны получить ответ с помощью кода.

Откройте файл ../data/lab01_train.csv с таблицей (не забудьте про её формат). Выведите последние 10 строк.

Посмотрите на данные и скажите, что они из себя представляют, сколько в таблице строк, какие столбцы? (на это не надо отвечать, просто подумайте об этом)

In [4]:
df = pd.read_csv(R'.\data\lab03_train.csv')
df.head(10)

,timestamp,id,rating,course_2,course_3,is_mi_student,is_ml_student,fall_1,fall_2,fall_3,spring_1,spring_2,spring_3,is_first_time,percentile,blended
0,2023-05-15 01:12:50,93ff79a51cd602f1dd3028ba2c129503,698,NaN,61.0,NaN,NaN,Язык SQL,Высокопроизводительные вычисления,Матричные вычисления,Дискретная оптимизация,Численные методы,Машинное обучение 2,Да,0.183857,NaN
1,2023-05-15 02:46:48,26b01b1c4cd5656bab18d24c548834fb,647,NaN,61.0,NaN,NaN,Высокопроизводительные вычисления,Безопасность компьютерных систем,Язык SQL,Дискретная оптимизация,Численные методы,Машинное обучение 2,Нет,0.426009,NaN
2,2023-05-15 03:12:41,30f3653fc176d54e89ac3179c455c6dd,624,NaN,65.0,NaN,NaN,Безопасность компьютерных систем,Матричные вычисления,Моделирование временных рядов,Дискретная оптимизация,Машинное обучение 2,Численные методы,Да,0.538117,NaN
3,2023-05-15 04:43:08,1528f0eaa027580820ccf0d92a53ad68,579,NaN,62.0,NaN,NaN,Statistical Learning Theory,Высокопроизводительные вычисления,Матричные вычисления,Дискретная оптимизация,Численные методы,Машинное обучение 2,Да,0.744395,NaN
4,2023-05-15 07:47:17,496ea4f0d4abe264b1bb1b80eb3830c5,572,NaN,63.0,NaN,NaN,Высокопроизводительные вычисления,Безопасность компьютерных систем,Теория баз данных,Компьютерные сети,Дискретная оптимизация,Численные методы,Да,0.780269,NaN
5,2023-05-15 09:10:18,d0d8ff53ed5b119f9056068e954256c6,591,NaN,67.0,NaN,NaN,Язык SQL,Statistical Learning Theory,Сбор и обработка данных с помощью краудсорсинга,Промышленное программирование на языке Java,Численные методы,Дискретная оптимизация,Да,0.690583,NaN
6,2023-05-15 11:42:16,e4caca755ee0bdd711e18fb8084958b5,724,NaN,62.0,NaN,NaN,Statistical Learning Theory,Безопасность компьютерных систем,Моделирование временных рядов,Численные методы,Промышленное программирование на языке Java,Машинное обучение 2,Да,0.103139,NaN
7,2023-05-15 12:11:43,8047c18b3c531c6f47931e0744f3e028,566,NaN,67.0,NaN,NaN,Язык SQL,Теория баз данных,Безопасность компьютерных систем,Промышленное программирование на языке Java,Компьютерные сети,Дискретная оптимизация,Да,0.802691,NaN
8,2023-05-15 13:21:40,e8b314842f176be9051d14a07cb156cb,618,NaN,61.0,NaN,NaN,Язык SQL,Теория баз данных,Матричные вычисления,Промышленное программирование на языке Java,Компьютерные сети,Дискретная оптимизация,Да,0.565022,NaN
9,2023-05-15 13:29:10,d6c079f1ff869c8c84fa3ed30bd67e0e,733,NaN,61.0,NaN,1.0,Теория баз данных,Высокопроизводительные вычисления,Сбор и обработка данных с помощью краудсорсинга,Дополнительные главы прикладной статистики,Анализ данных в бизнесе,Численные методы,Да,0.085202,NaN

Сколько было заявок от студентов второго курса, а сколько третьего курса?

In [5]:
number_of_request_course_2 = df['course_2'].notna().sum()
number_of_request_course_3 = df['course_3'].notna().sum()
#print(number_of_request_course_3)

In [6]:
assert number_of_request_course_2  == 138, 'Тест не пройден'
assert number_of_request_course_3 == 223, 'Тест не пройден'
print("Выполнено")
score += 0.5

Выполнено

Есть ли студенты с равными перцентилями?

In [7]:
is_equal_percentil = df['percentile'].duplicated().any()
#print(is_equal_percentil)

In [8]:
assert is_equal_percentil == True, 'Тест не пройден'
print("Выполнено")
score += 0.5

Выполнено

Есть ли в данных пропуски? В каких колонках? Сколько их в каждой из этих колонок?

In [9]:
course_2_na = df['course_2'].isna().sum()
course_3_na = df['course_3'].isna().sum()

is_mi_student_na = df['is_mi_student'].isna().sum()
is_ml_student_na = df['is_ml_student'].isna().sum()
is_first_time_na = df['is_first_time'].isna().sum()

blended_na = df['blended'].isna().sum()
percentile_na = df['percentile'].isna().sum()

print(is_ml_student_na)

304

In [10]:
assert course_2_na == 223, 'Тест не пройден'
assert course_3_na == 138, 'Тест не пройден'
assert is_mi_student_na == 343, 'Тест не пройден'
assert is_ml_student_na == 304, 'Тест не пройден'
assert blended_na == 223, 'Тест не пройден'
assert is_first_time_na == 0, 'Тест не пройден'
assert percentile_na == 0, 'Тест не пройден'

print("Выполнено")
score += 0.5

Выполнено

Заполните пропуски пустой строкой для строковых колонок и нулём для числовых.

In [11]:
#1 решение
df['course_2'] = df['course_2'].fillna(0)
df['course_3'] = df['course_3'].fillna(0)
df['is_mi_student'] = df['is_mi_student'].fillna(0)
df['is_ml_student'] = df['is_ml_student'].fillna(0)
df['is_first_time'] = df['is_first_time'].fillna('')
df['blended'] = df['blended'].fillna('')

df_na = df.isna().sum().sum()
df.head()

,timestamp,id,rating,course_2,course_3,is_mi_student,is_ml_student,fall_1,fall_2,fall_3,spring_1,spring_2,spring_3,is_first_time,percentile,blended
0,2023-05-15 01:12:50,93ff79a51cd602f1dd3028ba2c129503,698,0.0,61.0,0.0,0.0,Язык SQL,Высокопроизводительные вычисления,Матричные вычисления,Дискретная оптимизация,Численные методы,Машинное обучение 2,Да,0.183857,
1,2023-05-15 02:46:48,26b01b1c4cd5656bab18d24c548834fb,647,0.0,61.0,0.0,0.0,Высокопроизводительные вычисления,Безопасность компьютерных систем,Язык SQL,Дискретная оптимизация,Численные методы,Машинное обучение 2,Нет,0.426009,
2,2023-05-15 03:12:41,30f3653fc176d54e89ac3179c455c6dd,624,0.0,65.0,0.0,0.0,Безопасность компьютерных систем,Матричные вычисления,Моделирование временных рядов,Дискретная оптимизация,Машинное обучение 2,Численные методы,Да,0.538117,
3,2023-05-15 04:43:08,1528f0eaa027580820ccf0d92a53ad68,579,0.0,62.0,0.0,0.0,Statistical Learning Theory,Высокопроизводительные вычисления,Матричные вычисления,Дискретная оптимизация,Численные методы,Машинное обучение 2,Да,0.744395,
4,2023-05-15 07:47:17,496ea4f0d4abe264b1bb1b80eb3830c5,572,0.0,63.0,0.0,0.0,Высокопроизводительные вычисления,Безопасность компьютерных систем,Теория баз данных,Компьютерные сети,Дискретная оптимизация,Численные методы,Да,0.780269,

In [12]:
#2 решение
string_columns = df.select_dtypes(include='object').columns
number_columns = df.select_dtypes(include=np.number).columns

df[string_columns] = df[string_columns].fillna('')
df[number_columns] = df[number_columns].fillna(0)

df_na = df.isna().sum().sum() #счиатем пропуски по каждому столбцу, а потом общие
df.head()

,timestamp,id,rating,course_2,course_3,is_mi_student,is_ml_student,fall_1,fall_2,fall_3,spring_1,spring_2,spring_3,is_first_time,percentile,blended
0,2023-05-15 01:12:50,93ff79a51cd602f1dd3028ba2c129503,698,0.0,61.0,0.0,0.0,Язык SQL,Высокопроизводительные вычисления,Матричные вычисления,Дискретная оптимизация,Численные методы,Машинное обучение 2,Да,0.183857,
1,2023-05-15 02:46:48,26b01b1c4cd5656bab18d24c548834fb,647,0.0,61.0,0.0,0.0,Высокопроизводительные вычисления,Безопасность компьютерных систем,Язык SQL,Дискретная оптимизация,Численные методы,Машинное обучение 2,Нет,0.426009,
2,2023-05-15 03:12:41,30f3653fc176d54e89ac3179c455c6dd,624,0.0,65.0,0.0,0.0,Безопасность компьютерных систем,Матричные вычисления,Моделирование временных рядов,Дискретная оптимизация,Машинное обучение 2,Численные методы,Да,0.538117,
3,2023-05-15 04:43:08,1528f0eaa027580820ccf0d92a53ad68,579,0.0,62.0,0.0,0.0,Statistical Learning Theory,Высокопроизводительные вычисления,Матричные вычисления,Дискретная оптимизация,Численные методы,Машинное обучение 2,Да,0.744395,
4,2023-05-15 07:47:17,496ea4f0d4abe264b1bb1b80eb3830c5,572,0.0,63.0,0.0,0.0,Высокопроизводительные вычисления,Безопасность компьютерных систем,Теория баз данных,Компьютерные сети,Дискретная оптимизация,Численные методы,Да,0.780269,

In [13]:
assert df_na == 0, 'Тест не пройден'

print("Выполнено")
score += 0.5

Выполнено

Посмотрите повнимательнее на колонку 'is_first_time'. 
Есть ли в ней ответы "Нет"? Сколько их?

In [14]:
number_is_first_time_responses_no = (df['is_first_time'] == "Нет").sum()

In [15]:
assert number_is_first_time_responses_no == 52, 'Тест не пройден'
print("Выполнено")
score += 0.5

Выполнено

Если вы найдете повторные обращения студентов, оставьте только самую позднюю версию. 
<i>Обращения со значением "Нет" в <code>is_first_time</code> могут быть как повторными, так и первичными, поскольку поле заполняли сами студенты.</i>

In [16]:
df['timestamp'] = pd.to_datetime(df['timestamp']) #иначе считает как object
df= df.sort_values('timestamp') # по возрастанию (по умолч.)

df = df.drop_duplicates(subset='id', keep='last')
df = df.reset_index(drop=True)

total_number_of_request = len(df)

In [17]:
assert total_number_of_request == 347, 'Тест не пройден'
print("Выполнено")
score += 0.5

Выполнено

Какие  blended-курсы для второкурсников существуют?

In [18]:
blended_courses_for_second_year_students = set(df.loc[(df['course_2']!=0) & (df['blended']!=''), 'blended'])
#print(blended_courses_for_second_year_students) уникальный лист нужен

In [19]:
assert blended_courses_for_second_year_students == {'DevOps',
                                                   'Введение в дифференциальную геометрию',
                                                   'Соревновательный анализ данных'}, 'Тест не пройден'
print("Выполнено")
score += 0.5

Выполнено

На какой blended-курс записалось наибольшее количество студентов?

In [20]:
blended_course_with_max_request = df.loc[df['blended']!='', 'blended'].value_counts().idxmax()
#print(blended_course_with_max_request) надо вернуть именно индекс максимального

In [21]:
assert blended_course_with_max_request == 'DevOps', 'Тест не пройден'
print("Выполнено")
score += 0.5

Выполнено

На каком из курсов собрались студенты с самым высоким средним рейтингом?

In [22]:
average_rating = df.loc[df['blended']!=''].groupby('blended')['rating'].mean() #считаем средний рейтинг по курсам
print(average_rating)
course_with_highest_average_rating = average_rating.idxmax()

blended
DevOps                                   1154.172414
Введение в дифференциальную геометрию    1210.733333
Соревновательный анализ данных           1144.218750
Name: rating, dtype: float64

In [23]:
assert course_with_highest_average_rating == 'Введение в дифференциальную геометрию', 'Тест не пройден'
print("Выполнено")
score += 0.5

Выполнено

Выясните, есть ли в данных студенты с абсолютно одинаковыми предпочтениями по всем курсам (не забудьте учесть blended-курсы для третьекурсников). 
Сколько таких наборов, которые взяли несколько студентов? (по ответу подходит вопрос: сколько студентов?)

In [24]:
identical_combinations = df.groupby(['spring_1','spring_2','spring_3', 'fall_1', 'fall_2', 'fall_3','blended']).size() #названия в индексе series
reset_indx= identical_combinations.reset_index(name = 'number_of_students') #превращаем в dataframe
duplicate = reset_indx[reset_indx['number_of_students'] > 1] #там где дублируются, т.е. больше 1 повтора
number_duplicate_sets_of_courses = duplicate['number_of_students'].sum()
#number_duplicate_sets_of_courses = len(duplicate)
#print(identical_combinations)
print(reset_indx[:5])
#print(reset_indx[:2])
#print(duplicate[:4])
print(number_duplicate_sets_of_courses)

                  spring_1                spring_2  \
0  Анализ данных в бизнесе  Дискретная оптимизация
1  Анализ данных в бизнесе  Дискретная оптимизация
2  Анализ данных в бизнесе  Дискретная оптимизация
3  Анализ данных в бизнесе       Компьютерные сети
4  Анализ данных в бизнесе       Компьютерные сети

                                      spring_3  \
0                           Системы баз данных
1                           Системы баз данных
2                             Численные методы
3                          Машинное обучение 2
4  Промышленное программирование на языке Java

                                              fall_1  \
0                        Statistical Learning Theory
1                   Безопасность компьютерных систем
2                        Statistical Learning Theory
3                   Безопасность компьютерных систем
4  Принятие решений в условиях риска и неопределё...

                              fall_2  \
0               Матричные вычисления
1      Моделирование временных рядов
2                           Язык SQL
3        Statistical Learning Theory
4  Высокопроизводительные вычисления

                                              fall_3 blended  \
0                      Моделирование временных рядов
1  Принятие решений в условиях риска и неопределё...
2  Принятие решений в условиях риска и неопределё...
3    Сбор и обработка данных с помощью краудсорсинга
4                                           Язык SQL

   number_of_students
0                   1
1                   1
2                   1
3                   1
4                   1
32

In [25]:
assert number_duplicate_sets_of_courses == 32, 'Тест не пройден'
print("Выполнено")
score += 0.5

Выполнено

Выведите все дублирующиеся наборы курсов, вместе с количеством выбравших их студентов.

<i>Предпочтения двух студентов считаются абсолютно одинаковыми, если выбранные ими дисциплины имеют одинаковый приоритет.</i>

In [26]:
duplicate_sets_of_courses_with_number_students = duplicate.reset_index(drop=True) # сбиваем индекс в привычный 0...347
#print(duplicate_sets_of_courses_with_number_students)

In [27]:
duplicate_sets_of_courses_with_number_students_answer = pd.read_csv('./data/duplicate_sets_of_courses_with_number_students.csv').fillna(value={'blended': '',})
assert duplicate_sets_of_courses_with_number_students.equals(duplicate_sets_of_courses_with_number_students_answer), 'Тест не пройден'

print("Выполнено")
score += 0.5

Выполнено

Найдите курсы по выбору, на которые записывались как студенты второго, так и студенты третьего курса.

In [28]:
seasons = ['spring_1','spring_2','spring_3', 'fall_1', 'fall_2', 'fall_3']
students_2 = df[df['course_2'] != 0]

courses_only_2 = (set(students_2['fall_1']) | set(students_2['fall_2']) | set(students_2['fall_3']) | set(students_2['spring_1']) | set(students_2['spring_2']) | set(students_2['spring_3']))


students_3 = df[df['course_3'] != 0]
courses_only_3 = (set(students_3['fall_1']) | set(students_3['fall_2']) | set(students_3['fall_3']) | set(students_3['spring_1']) | set(students_3['spring_2']) | set(students_3['spring_3']))


courses_students_of_2_and_3_year = (courses_only_2 & courses_only_3)
#print(courses_students_of_2_and_3_year)

In [29]:
assert courses_students_of_2_and_3_year == {'Численные методы',
                                            'Statistical Learning Theory',
                                            'Безопасность компьютерных систем',
                                            'Сбор и обработка данных с помощью краудсорсинга',
                                            'Высокопроизводительные вычисления',
                                            'Принятие решений в условиях риска и неопределённости',
                                            'Моделирование временных рядов'}, 'Тест не пройден'
print("Выполнено")
score += 0.5

Выполнено

Методом исключения найдите курсы, которые выбрали только студенты второго курса и только студенты третьего курса.

In [30]:
courses_only_2_year = courses_only_2 - courses_only_3
courses_only_3_year = courses_only_3 - courses_only_2

#print(courses_only_3)

In [31]:
assert courses_only_2_year == {'Анализ неструктурированных данных',
                               'Байесовские методы машинного обучения',
                               'Генеративные модели в машинном обучении',
                               'Глубинное обучение в обработке звука',
                               'Компьютерное зрение',
                               'Конфликты и кооперация',
                               'Методы сжатия и передачи медиаданных',
                               'Обучение с подкреплением',
                               'Проектирование и разработка высоконагруженных сервисов',
                               'Символьные вычисления'}, 'Тест не пройден'

assert courses_only_3_year == {'Анализ данных в бизнесе',
                               'Дискретная оптимизация',
                               'Дополнительные главы прикладной статистики',
                               'Компьютерные сети',
                               'Матричные вычисления',
                               'Машинное обучение 2',
                               'Промышленное программирование на языке Java',
                               'Системы баз данных',
                               'Теория баз данных',
                               'Язык SQL'}, 'Тест не пройден'

print("Выполнено")
score += 0.5

Выполнено

## Часть 2. Распределение студентов по курсам

Теперь вам нужно распределить студентов по осенним курсам по выбору, учитывая их предпочтения.

Алгоритм распределения студентов по курсам:
1. По умолчанию на каждой дисциплине по выбору у 2 и 3 курсов может учиться 1 группа (до 30 студентов). Исключения описаны ниже. На blended-дисциплинах для третьекурсников количество мест не ограничено.
2. Проводится первая волна отбора. Для каждой дисциплины формируется список тех, кто указал её первым приоритетом (если студент должен выбрать два курса по выбору, то для него дисциплины, которые он указал первым и вторым приоритетом, рассматриваются как дисциплины первого приоритета). Если желающих больше, чем мест, то выбирается топ по перцентилю рейтинга.
3. На дисциплинах, где остались места после первой волны, формируются списки тех, кто выбрал их вторым приоритетом, и места заполняются лучшими по перцентили рейтинга студентами. После этого проводится такая же процедура для дисциплин третьего приоритета.
4. Если студент не попал на необходимое количество курсов по итогам трёх волн, с ним связывается учебный отдел и решает вопрос в индивидуальном порядке.


Обращаем ваше внимание на следующие детали:

- По умолчанию студент выбирает один осенний и один весенний курс по выбору, а также третьекурсники выбирают один blended-курс. Студенты групп третьего курса специализаций МОП и ТИ выбирают по 2 осенних и 2 весенних курса по выбору, также студенты групп второго курса специализации МИ выбирают 2 осенних курса. <i>Для студентов, которые выбирают 2 курса (например, осенних) первый приоритет — <code>fall_1</code> и <code>fall_2</code>, второй приоритет — <code>fall_3</code>. Такие студенты участвуют только в двух волнах отбора</i>.

- Студенты специализации МОП не могут выбрать весенним курсом по выбору Машинное обучение 2. <i>Если студент специализации МОП выбрал Машинное обучение 2, то его приоритеты сдвигаются. Из-за совпадений первого и второго курса по выбору двигать приоритеты не надо</i>.

- Blended-курсы не трогайте, по ним не надо распределять, на другие курсы они никак не влияют.

- Постарайтесь воздержаться от использования циклов там, где это возможно. <i>Допустимо итерироваться по <b>курсам</b>, на которые проводится отбор, и по <b>волнам</b> отбора. Если вы придумаете, как обойтись и без этих циклов, то на усмотрение проверяющего могут быть добавлены бонусные баллы. <b>Дублирование кода не признается успешным избавлением от циклов</b></i>

- На выходе ожидается файл res_fall.csv с результатами распределения на осенние курсы по выбору. Файл должен быть следующего формата:

    * три столбца: ID, course1, course2
    
    * Если студент не попал на курс, но должен был, то вместо названия курса в ячейке должна быть строка "???"
    
    * Если студент должен выбрать только один курс, то в колонке course2 для него должна стоять строка "-"
    
    * Если студент должен выбрать два курса по выбору, то порядок в колонках course1 и course2 не важен.
    
    * Формат csv: для сохранения воспользуйтесь df.to_csv('solution.csv', index=None)
    

Для работы вам могут понадобиться следующие данные:

- Результаты опроса (вы уже использовали этот файл в первой части задания)

- Соответствие номеров групп специализациям:

    * 61, 62 - МОП; 63 - ТИ; 64 — АДИС; 65, 66 — РС; 67 — АПР
    
    * У студентов второго курса номера групп соответствуют номерам до распределения по специализациям.

- Ограничения по количеству мест на курсах по выбору:

    * Осенние: везде 30 мест, кроме Statistical Learning Theory (60 мест), Высокопроизводительных вычислений (60 мест), Анализа неструктурированных данных ($\infty$ мест)

    * Весенние: везде 30 мест, кроме Обучения с подкреплением (60 мест), Анализа данных в бизнесе (60 мест).


Кстати, убедитесь, что в данных больше нет пропусков и повторных записей.

#### Проверка

Для начала давайте убедимся, что вы успешно выполнили задания первой части и проверим ваши данные на наличие пропусков и повторов:

In [32]:
assert df.shape[0] == 347, 'В таблице остались повторы или потеряны данные'

assert df.isna().sum().sum() == 0, 'В таблице остались пропуски'

Если вы не получили AssertionError, то можете продолжать.

Создайте новый признак, обозначающий, сколько осенних курсов должен выбрать студент
В этом вам может помочь информация о специализации и группе стундента.

In [33]:
#можно выбрать только 1 курс по умолчанию, но 3 курс специализации МОП (гр. 61, 62) и ТИ (гр. 63) - 2 курса , 2 курс специализации МИ 2 курса (столбец is_mi_student=1)

df['fall_course_num'] = 1

df.loc[df['course_3'].isin([61, 62, 63]), 'fall_course_num'] = 2 # если есть в группе, то ставим 2 курса

df.loc[df['is_mi_student'] == 1, 'fall_course_num'] = 2 # если учится в МИ, то 2 курса

df[['course_2', 'course_3', 'is_mi_student','fall_course_num']].head(20)

    course_2  course_3  is_mi_student  fall_course_num
0       42.0       0.0            0.0                1
1       46.0       0.0            0.0                1
2       42.0       0.0            0.0                1
3       41.0       0.0            0.0                1
4       46.0       0.0            0.0                1
5       46.0       0.0            0.0                1
6       45.0       0.0            0.0                1
7       45.0       0.0            0.0                1
8       43.0       0.0            0.0                1
9       42.0       0.0            0.0                1
10      42.0       0.0            0.0                1
11      45.0       0.0            0.0                1
12      45.0       0.0            0.0                1
13      43.0       0.0            0.0                1
14      46.0       0.0            0.0                1
15      45.0       0.0            0.0                1
16      43.0       0.0            0.0                1
17      43.0       0.0            0.0                1
18       0.0      61.0            0.0                2
19       0.0      61.0            0.0                2

Проверка:

In [34]:
col_name = 'fall_course_num'

assert(df[df['id'] == '2662600c2c37e11e62f6ee0b88452f22'][col_name] == 2).all(), 'Тест не пройден'
assert(df[df['id'] == 'd555d2805e1d93d4f023e57dc4c8f403'][col_name] == 1).all(), 'Тест не пройден'
assert(df[df['id'] == '8fe79f84f36e3a5d2d6745621321302c'][col_name] == 1).all(), 'Тест не пройден'
assert(df[df['id'] == 'e4caca755ee0bdd711e18fb8084958b5'][col_name] == 2).all(), 'Тест не пройден'

print("Выполнено")
score += 1.5

Выполнено

Распределите студентов в соответствии с первым приоритетом

Здесь для проверки приведена таблица, в которой есть 2 дополнительные колонки:

    1) is_first_place - является ли студент лучшим по перцентили хотя бы на одном из курсов, куда он был зачислен 
    (True / NaN)
    
    2) is_last_place  - является ли студент худшим по перцентили хотя бы на одном из курсов, куда он был зачислен (True / NaN)

In [35]:
check_df = pd.read_csv('./data/lab03_train_check.csv')
check_df.head()

,timestamp,id,rating,course_2,course_3,is_mi_student,is_ml_student,fall_1,fall_2,fall_3,spring_1,spring_2,spring_3,is_first_time,percentile,blended,is_first_place,is_last_place
0,2020-05-15 01:12:50.543,93ff79a51cd602f1dd3028ba2c129503,698,NaN,61.0,0.0,0.0,Язык SQL,Высокопроизводительные вычисления,Матричные вычисления,Дискретная оптимизация,Численные методы,Машинное обучение 2,Да,0.183857,NaN,NaN,NaN
1,2020-05-15 02:46:48.066,26b01b1c4cd5656bab18d24c548834fb,647,NaN,61.0,0.0,0.0,Высокопроизводительные вычисления,Безопасность компьютерных систем,Язык SQL,Дискретная оптимизация,Численные методы,Машинное обучение 2,Нет,0.426009,NaN,NaN,NaN
2,2020-05-15 03:12:41.480,30f3653fc176d54e89ac3179c455c6dd,624,NaN,65.0,0.0,0.0,Безопасность компьютерных систем,Матричные вычисления,Моделирование временных рядов,Дискретная оптимизация,Машинное обучение 2,Численные методы,Да,0.538117,NaN,NaN,NaN
3,2020-05-15 04:43:08.994,1528f0eaa027580820ccf0d92a53ad68,579,NaN,62.0,0.0,0.0,Statistical Learning Theory,Высокопроизводительные вычисления,Матричные вычисления,Дискретная оптимизация,Численные методы,Машинное обучение 2,Да,0.744395,NaN,NaN,NaN
4,2020-05-15 07:47:17.197,496ea4f0d4abe264b1bb1b80eb3830c5,572,NaN,63.0,0.0,0.0,Высокопроизводительные вычисления,Безопасность компьютерных систем,Теория баз данных,Компьютерные сети,Дискретная оптимизация,Численные методы,Да,0.780269,NaN,NaN,NaN

После распределения студентов в соответствии с первым приоритетом добавьте в свой датафрейм аналогичные признаки и запустите проверку:

Проведите все три волны отбора студентов на курсы по выбору
Результат сохраните в файл res_fall.csv.

In [36]:
# нужен 1 курс = fall_1, 2 курса - fall_1 + fall_2 (первый приоритет), если мест не хватает (max = 30), то смотрим в процентиль/percentile
# Statistical Learning Theory - 60 мест, Высокопроизводительные вычисления - 60 мест, Анализ неструкт. данных - без ограничений)

fall_courses = sorted((set(df['fall_1']) | set(df['fall_2']) | set(df['fall_3'])) - {''}) # все уникальные осенние курсы и сортируем по алфавиту
#print(fall_cources)

places = {} # кол-во мест

#запоняем места
for course in fall_courses:
    places[course] = 30
    
#print(places)    
    
places['Statistical Learning Theory'] = 60
places['Высокопроизводительные вычисления'] = 60
places['Анализ неструктурированных данных'] = np.inf

free_places = places.copy() # учет свободных мест

df['course1'] = '???'
df['course2'] = '???'
df.loc[df['fall_course_num'] == 1, 'course2'] = '-' #если второй курс не выбирается, то - должен быть

#создаем ячейки, которые потом проверяться будут рейтинг
df['is_first_place'] = pd.Series(pd.NA, index=df.index, dtype='boolean')
df['is_last_place'] = pd.Series(pd.NA, index=df.index, dtype='boolean')

for wave in [1, 2, 3]: 
      
    for course in fall_courses:
        
        if wave == 1:
            
            one_cource_priority = (df['fall_course_num'] == 1) & (df['fall_1'] == course) # тому, кому нужен 1 курс мы доавляем по первому приоритету (true/false)
            two_cource_priority = (df['fall_course_num'] == 2) & ((df['fall_1'] == course) | (df['fall_2'] == course)) #2 курса и по первым двум приоритетам проверяем (true/false)
            #print(one_cource_priority)
            
            priority = (one_cource_priority | two_cource_priority) #те, кто попадает в волну
            
        elif wave == 2:
            
            one_cource_priority = (df['fall_course_num'] == 1) & (df['fall_2'] == course) # для студентов с одним курсом, где fall_2 = второй приоритет
            two_cource_priority = (df['fall_course_num'] == 2) & (df['fall_3'] == course) #2 курса и ппроверяем уже по 3 приоритету
            
            priority = (one_cource_priority | two_cource_priority)
            
        else:
            
            priority = (df['fall_course_num'] == 1) & (df['fall_3'] == course)# здесь нужен только студентам с одним курсом
            
        if_needs_course = ((df['course1'] == '???') | ((df['fall_course_num'] == 2) & (df['course2'] == '???'))) # если нужен еще курс
        not_in_course = ((df['course1'] != course) & (df['course2'] != course)) # не записан ли студент на курс уже
            
        candidates = df[priority & if_needs_course & not_in_course] # склеиваем DataFrame и получаем всех желающих

        #print(candidates)

        candidates = candidates.sort_values('percentile') # сортируем от лучший к худшим

        # выбираем поступивших
        if free_places[course]  == np.inf:
            chosen = candidates
        else:
            chosen = candidates.head(int(free_places[course]))
            
        if len(chosen) == 0:
            continue
        
        first_course = chosen[chosen['course1'] == '???'].index # берем студентов, у которых первый курс не выбран и получем их индексы
        second_course = chosen[(chosen['fall_course_num'] == 2) & (chosen['course1'] != '???') & (chosen['course2'] == '???')].index # находим индексы для студентов, где 1 уже выбран, а 2 еще нет
        #print(first_course)
        
        
        # подставляем значения
        df.loc[first_course, 'course1'] = course 
        df.loc[second_course, 'course2'] = course
        
        if free_places[course] != np.inf:
            free_places[course] -= (len(first_course) + len(second_course))
        

        if wave == 1:
            
            students = df[(df['course1'] == course) | (df['course2'] == course)]

            if len(students) == 0:
                continue

            best = students['percentile'].min()
            worst = students['percentile'].max()

            best_students = students[students['percentile'] == best].index
            last_students = students[students['percentile'] == worst].index

            df.loc[best_students, 'is_first_place'] = True
            df.loc[last_students, 'is_last_place'] = True
    
        
res_fall = df[['id', 'course1', 'course2']].copy()
res_fall.to_csv('res_fall.csv', index=None)

res_fall.head(25)

,id,course1,course2
0,d555d2805e1d93d4f023e57dc4c8f403,Глубинное обучение в обработке звука,-
1,253bbe1a2021d0404712a1e4acd22939,Statistical Learning Theory,-
2,881b1a6fda195b354ae2edb396a69f5d,Анализ неструктурированных данных,-
3,5a9b8ac11ad05b39a58b0e04a263bf4c,Глубинное обучение в обработке звука,-
4,1bbbfae51794b83c769b634be8da7b8d,Анализ неструктурированных данных,-
5,8c3aa7371731bef999519c3de2c47423,Анализ неструктурированных данных,-
6,1b7e1b30238f393811a2b48c6f6a060f,Высокопроизводительные вычисления,-
7,d670dfbe253658a4e427a5569c59de9e,Высокопроизводительные вычисления,-
8,3a7326c9e355a67d3805824ca34c4bc5,Statistical Learning Theory,-
9,2ca6917be428f8b84f6f15cdcbea2143,Анализ неструктурированных данных,-
10,3e88c8d53bcd73595d2bbcdd8c51c1bf,Байесовские методы машинного обучения,-
11,308ec2ced0092de5474a1a8f4c0bfcfd,Высокопроизводительные вычисления,-
12,8e8d87fd686122d2c061d7b1eea2d3c5,Высокопроизводительные вычисления,-
13,5d1deb0ae3a69348a018881ac785fd90,Высокопроизводительные вычисления,-
14,e242616383e4cb90672c3dbcf146bf3b,Безопасность компьютерных систем,-
15,e22f8203911170e6b68b1b88cf85fee2,Высокопроизводительные вычисления,-
16,e0fceae1e285f737630bb6123a1bd85d,Высокопроизводительные вычисления,-
17,276e2ccf4903d4ddf856b20a2b08394e,Байесовские методы машинного обучения,-
18,93ff79a51cd602f1dd3028ba2c129503,Высокопроизводительные вычисления,Язык SQL
19,26b01b1c4cd5656bab18d24c548834fb,Высокопроизводительные вычисления,???
20,30f3653fc176d54e89ac3179c455c6dd,Матричные вычисления,-
21,1528f0eaa027580820ccf0d92a53ad68,Statistical Learning Theory,Высокопроизводительные вычисления
22,496ea4f0d4abe264b1bb1b80eb3830c5,Высокопроизводительные вычисления,Теория баз данных
23,d0d8ff53ed5b119f9056068e954256c6,Язык SQL,-
24,e4caca755ee0bdd711e18fb8084958b5,Statistical Learning Theory,Безопасность компьютерных систем

Проверка:

In [37]:
assert((df[df['is_first_place'].isna() == False][['id']].sort_values('id').reset_index(drop=True)
        ==
        check_df[check_df['is_first_place'].isna() == False][['id']].sort_values('id').reset_index(drop=True)
       ).id.values).all()


assert((df[df['is_last_place'].isna() == False][['id']].sort_values('id').reset_index(drop=True)
       == 
       check_df[check_df['is_last_place'].isna() == False][['id']].sort_values('id').reset_index(drop=True)
      ).id.values).all()

print("Выполнено")
score += 2

Выполнено

In [38]:
# общий балл
score

10.0